version: '1.0.0'

services:
  api:
    build: .
    env_file: ./app/.env
    
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000
